### ISSUE TITLE
refactor!: create single subnet delegation

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-network#16]
Figure out if multiple subnet delegations are actually supported. If not, a breaking change should be implemented to only allow a single delegation instead of a list of delegations.

https://github.com/equinor/terraform-azurerm-network/blob/f59214f99d33a3c46c938d69aad4fe05d414d4a6/variables.tf#L47-L51

**Comment by hknutsen** [comment]
When exporting a subnet to JSON, the value of `delegations` is a list. So seems like it does indeed accept a list. Thus this issue might prove irrelevant.

**Comment by kov117** [comment]
should we close this issue then ?

**Comment by hknutsen** [comment]
I'd prefer to have tested if this assumption is true or not before closing 🙂
