### ISSUE TITLE
feat(nsg)!: create diagnostic setting

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-network#33]
Investigate what logs are available for NSGs, and consider if any of these should be enabled in our `nsg` submodule.

**Comment by hknutsen** [comment]
Marks as breaking change, as this would require a new required variable `log_analytics_workspace_id`.

**Comment by kov117** [comment]
There are 3 logs available for NSG's, NetworkSecurityGroupEvent, NetworkSecurityGroupFlowEvent, and NetworkSecurityGroupRuleCounter. 
The NSG Event are logged for which NSG rules are applied to VMs, based on MAC address. 
NSGFlowEvent is for recording all IP flows going in and out of NSG. 
The NSG Rule counter contains entries for how many times each NSG rule is applied to deny or allow traffic. 

Seeing how they each have good uses and have no cost to export, i believe having all of them would be beneficial to the submodule `nsg` 

Ref.
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs-categories#microsoftnetworknetworksecuritygroups

https://stackoverflow.com/questions/75213897/difference-between-azure-networksecuritygroupevents-and-networksecuritygroupflow

https://github.com/MicrosoftDocs/azure-docs/issues/55369

**Comment by kov117** [comment]
More research shows that Network security flow event is not usable, an error messages showed that it would require a feature, as shown below.
`Error: creating Monitor Diagnostics Setting "audit-logs" for Resource "/subscriptions/ce8c6461-a20d-47a3-884c-6659cb74e53f/resourceGroups/rg-41a1fe6638abb6b5/providers/Microsoft.Network/networkSecurityGroups/nsg-41a1fe6638abb6b5": diagnosticsettings.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Category 'NetworkSecurityGroupFlowEvent' requires feature 'AllowNsgFlowLogging' in 'Registered' state, which differs from current state 'NotRegistered' for subscription 'ce8c6461-a20d-47a3-884c-6659cb74e53f'."`

Also the metric will be set to false as NSG does not have metric logs.

**Comment by kov117** [comment]
i will also fix an issue involving public ip, there was an error when i merged a branch to the main where instead of only pulling the module public ip, i pulled along with it resource public ip, which was supposed to be replased with the module public ip.
